<?php

/**
 * Implements hook_views_api().
 */
function gsb_media_center_views_api($module, $api) {
  if ($module == "views" && $api == "views_default") {
    return array(
      'version' => '3.0',
      'path' => drupal_get_path('module', 'gsb_media_center') .'/includes',
    );
  }
}

/**
 * Implements hook_forms().
 */
function gsb_media_center_forms() {
  $forms['gsb_media_center_add_files_and_docs_upload'] = array(
    'callback' => 'file_entity_add_upload',
  );

  $forms['gsb_media_center_add_image_upload'] = array(
    'callback' => 'file_entity_add_upload',
  );

  $forms['gsb_media_center_add_video_upload'] = array(
    'callback' => 'media_internet_add',
  );

  return $forms;
}

/**
 * Implements hook_form_alter().
 */
function gsb_media_center_form_views_exposed_form_alter(&$form, &$form_state) {
  global $user;
  if (isset($form['field_sections_tid']) && !isset($form_state['input']['sections_processed'])) {
    dsm($user);
    // Keeps track if we've already processed the section.
    $form['sections_processed'] = array(
      '#type' => 'hidden',
      '#value' => TRUE,
    );

    $new_default = array();
    foreach($form['field_sections_tid']['#options'] as $key => $value) {
      $new_default[$key] = $key;
    }

    $form['field_sections_tid']['#default_value'] = $new_default;
    $form_state['input']['field_sections_tid'] = $new_default;

  }
}
